//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chmo
{
    using System;
    using System.Collections.Generic;
    
    public partial class otchet
    {
        public int id { get; set; }
        public Nullable<double> profit { get; set; }
        public Nullable<double> loss { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
    }
}
