//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chmo
{
    using System;
    using System.Collections.Generic;
    
    public partial class workerDate
    {
        public int id { get; set; }
        public Nullable<int> id_worker { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> minimal { get; set; }
        public Nullable<double> profit { get; set; }
    
        public virtual worker worker { get; set; }
    }
}
